name: Codeforces Reminder Bot

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
          PHONE_NUMBER_ID: ${{ secrets.PHONE_NUMBER_ID }}
          WHATSAPP_TO: ${{ secrets.WHATSAPP_TO }}
        run: python main.py
